spring.application.name=productos-api

#Configuración de base de datos

spring.datasource.url=jdbc:h2:mem:productsdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

#JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# external-api.categories-url=https://api.escuelajs.co/api/v1/categories

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
