INSERT INTO productos (nombre, precio, stock, id_categoria) VALUES
                                                                ('Remera de Algodón Clásica', 15000.00, 35, 1),
                                                                ('Jean de Corte Slim', 42000.00, 20, 1),
                                                                ('Buzo Básico', 38000.00, 18, 1),
                                                                ('Campera de Invierno', 85000.00, 10, 1),
                                                                ('Short de Algodón', 22000.00, 25, 1),
                                                                ('Camisa Casual', 30000.00, 15, 1),
                                                                ('Remera Deportiva', 18000.00, 40, 1),
                                                                ('Chomba Clásica', 27000.00, 22, 1),
                                                                ('Mouse Inalámbrico', 25000.00, 30, 2),
                                                                ('Teclado Mecánico', 75000.00, 15, 2),
                                                                ('Cable USB-C', 12000.00, 50, 2),
                                                                ('Auriculares Bluetooth', 65000.00, 12, 2),
                                                                ('Monitor Gamer 24"', 220000.00, 8, 2),
                                                                ('Cargador Inalámbrico', 28000.00, 25, 2),
                                                                ('SSD Portátil 1TB', 145000.00, 10, 2),
                                                                ('Silla de Oficina', 120000.00, 8, 3),
                                                                ('Escritorio de Madera', 180000.00, 6, 3),
                                                                ('Biblioteca', 95000.00, 12, 3),
                                                                ('Mesa de Luz', 55000.00, 14, 3),
                                                                ('Silla de Comedor', 70000.00, 20, 3),
                                                                ('Escritorio para Computadora', 135000.00, 9, 3),
                                                                ('Zapatillas Casuales', 58000.00, 18, 4),
                                                                ('Zapatos Clásicos de Cuero', 90000.00, 10, 4),
                                                                ('Zapatillas Deportivas', 72000.00, 13, 4),
                                                                ('Sandalias de Verano', 35000.00, 25, 4),
                                                                ('Mochila de Viaje', 55000.00, 20, 5),
                                                                ('Botella de Agua', 15000.00, 35, 5),
                                                                ('Lámpara de Escritorio', 30000.00, 16, 5),
                                                                ('Cuaderno A5', 8000.00, 50, 5),
                                                                ('Taza de Café', 10000.00, 30, 5),
                                                                ('Soporte para Teléfono', 14000.00, 24, 5);