INSERT INTO productos (nombre, precio, stock, id_categoria) VALUES
                                                                ('Classic Cotton T-Shirt', 15000.00, 35, 1),
                                                                ('Slim Fit Jeans', 42000.00, 20, 1),
                                                                ('Basic Hoodie', 38000.00, 18, 1),
                                                                ('Winter Jacket', 85000.00, 10, 1),
                                                                ('Cotton Shorts', 22000.00, 25, 1),
                                                                ('Casual Shirt', 30000.00, 15, 1),
                                                                ('Sport T-Shirt', 18000.00, 40, 1),
                                                                ('Classic Polo Shirt', 27000.00, 22, 1),
                                                                ('Wireless Mouse', 25000.00, 30, 2),
                                                                ('Mechanical Keyboard', 75000.00, 15, 2),
                                                                ('USB-C Cable', 12000.00, 50, 2),
                                                                ('Bluetooth Headphones', 65000.00, 12, 2),
                                                                ('Gaming Monitor 24"', 220000.00, 8, 2),
                                                                ('Wireless Charger', 28000.00, 25, 2),
                                                                ('Portable SSD 1TB', 145000.00, 10, 2),
                                                                ('Office Chair', 120000.00, 8, 3),
                                                                ('Wooden Desk', 180000.00, 6, 3),
                                                                ('Bookshelf', 95000.00, 12, 3),
                                                                ('Night Table', 55000.00, 14, 3),
                                                                ('Dining Chair', 70000.00, 20, 3),
                                                                ('Computer Desk', 135000.00, 9, 3),
                                                                ('Casual Sneakers', 58000.00, 18, 4),
                                                                ('Classic Leather Shoes', 90000.00, 10, 4),
                                                                ('Sports Shoes', 72000.00, 13, 4),
                                                                ('Summer Sandals', 35000.00, 25, 4),
                                                                ('Travel Backpack', 55000.00, 20, 5),
                                                                ('Water Bottle', 15000.00, 35, 5),
                                                                ('Desk Lamp', 30000.00, 16, 5),
                                                                ('Notebook A5', 8000.00, 50, 5),
                                                                ('Coffee Mug', 10000.00, 30, 5),
                                                                ('Phone Stand', 14000.00, 24, 5);